"""create revision --autogenerate

Revision ID: 695604cd776d
Revises: 6fe8b1f53f88
Create Date: 2026-05-15 13:28:15.349500-03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '695604cd776d'
down_revision: Union[str, Sequence[str], None] = '6fe8b1f53f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    op.drop_table('empresa_ativa')
    op.drop_table('empresa_inativa')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa_inativa',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cnpj', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('razao_social', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('nome_fantasia', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cod_logradouro', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('nome_logradouro', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('numero_residencia', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('numero_lote', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('cod_bairro', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('nome_bairro', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('situacao_empresa', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('data_abertura_empresa', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('data_encerramento', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('cod_grupo', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('nome_grupo', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('cnae', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('desc_atividade', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('atividade_principal', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('atividade_vig_sanitaria', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('atividade_predominante', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('incomodo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('empresa_inativa_pkey'))
    )
    op.create_table('empresa_ativa',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cnpj', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('razao_social', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('nome_fantasia', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cod_logradouro', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('nome_logradouro', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('numero_residencia', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('numero_lote', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('cod_bairro', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('nome_bairro', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('situacao_empresa', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('data_abertura_empresa', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('data_encerramento', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('cod_grupo', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('nome_grupo', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('cnae', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('desc_atividade', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('atividade_principal', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('atividade_vig_sanitaria', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('atividade_predominante', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('incomodo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('empresa_ativa_pkey'))
    )
    op.create_table('account',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('last_transaction_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('account_pkey'))
    )
    # ### end Alembic commands ###
